### ISSUE TITLE
Typo at file dispenser_sand_bonemealing.yml

### ISSUE THREAD

**Issue by Slachy-Dot** [Jishuna/MineTweaks#13]
# Enable or disable this tweak.
enabled: true

# Whether to allow this feature to work on normal sand.
allow-normal-sand: true
# Whether to allow this feature to work on red sand.
allow-red-sand: true

# Display name, seen in-game
display-name: "Dispenser Cauldron Filling"

# Description, seen in-game
description: "Allows dispensers to fill cauldrons with buckets."

# Category
category: "Dispensers"

its using some stuff from cauldrons with buckets

**Comment by The-Epic** [comment]
Whats the actual spelling issue on this?

**Comment by Slachy-Dot** [comment]
display-name: "Dispenser Cauldron Filling"
description: "Allows dispensers to fill cauldrons with buckets."

these both dont belong on this file as its for sand bonemealing not filling cauldron

**Comment by Jishuna** [comment]
Fixed
