### ISSUE TITLE
1.19 Mob head on note block doesn't seem to work

### ISSUE THREAD

**Issue by mistermsk** [Jishuna/MineTweaks#14]
When placing a mob head (cow, creeper, etc...) on note block. The note block just puts out it sound and not the mobs sound.

1.19

Config:
# Enable or disable this tweak.
enabled: true

# Display name, seen in-game
display-name: "Mob Head Noteblocks"

# Description, seen in-game
description: "Makes note blocks with mob heads attached to them play the mobs sound."

# Category
category: "Blocks"

**Comment by Jishuna** [comment]
All vanilla mob heads appear to be working fine (Creeper, Zombie, Skeleton, Wither Skeleton, Dragon). Any custom mob heads are not currently supported, as there are many varieties of these available.
