### ISSUE TITLE
Tweak disabling doesn't work

### ISSUE THREAD

**Issue by Fenix5fire** [Jishuna/MineTweaks#6]
For the some unknown reason some disabled tweaks works as it is enabled, leather from rotten flesh that disabled by DEFAULT for example. First I thought that I messed plugin by loading it on currently working server, but reloading configs, server itself or plugin reinstalling didn't help at all. Problem goes out from the box.  My server running on airplane-purpur 1.17.1 with Java 16 and the issue remains even on fresh server, so other plugins doesn't cause this issue. Also tried to launch it on Paper, but nothing changed. No errors or something occured. 

I can 100% tell that crafting table in inventory works even if it is disabled, but enderchest or crop harvesting doesn't.

**Comment by Jishuna** [comment]
Recipes being registered when disabled has been fixed. 
I am unable to replicate crafting table in inventory working when disabled. If you can still reproduce this, feel free to re-open this issue with the steps to do so.
